### ISSUE TITLE
Continuous TODO list

### ISSUE THREAD

**Issue by wintercounter** [wintercounter/mhy#1]
# Done (keeping them just because it looks cool)
- [x] ~Refact the code to make it easier for other maintainers start on it easily~
- [x] ~`Typescript` support -> config~
- [x] ~Create documentation~
- [x] ~Official website~
- [x] ~Add command registering interface instead of implementing all commands in mhy~
- [x] ~Add CI for dist (along with sub-packages) + Docker image~
- [x] ~Update dependencies (being done continously)~
- [x] ~Remove `postcss-cssnext` in the favor of `postcss-preset-env`~
- [x] ~Rename @mhy/mhy to `mhy`~
- [x] ~`Prettier` refakt: detach from Babel, use Process~
- [x] ~Add `Prettier` to all available extensions it is supporting~
- [x] ~Add `*Storm` configuration docs~
- [x] ~Add `VSCode` configuration docs~
- [x] ~Make folders configurable (like src)~
- [x] ~Add `mhy` config, single source for stuffs like extensions, directories, etc.~
- [x] ~Implement a solution for correct array manipulation from package.json~
- [x] ~Add `webpack-bundle-analyzer` process~
- [x] ~Add `tslint` process~
- [x] ~Deprecate other mhy repositories and packages~
- [x] ~Appriciation option for contributors and dependency developers~
- [x] ~Add `standalone storybook` support~
- [x] ~Pass flags to WDS~
- [x] ~Make _console_ functions allowed by **eslint** using _development_ `NODE_ENV`~
- [x] ~Measure `babel-loader` cache options if compilation can be speed up~
- [x] ~Add `jimp` process (cancelled)~

# Next
- [ ] Create more examples
- [ ] More CLI ouput tests
- [ ] Create repository with test projects
- [ ] Add missing community profile pages
- [ ] Use `svgr-loader` instead of `react-svg-loader` (also investigate the removal of svgx extension)
- [ ] Add `GraphQL` toys (with GraphQL Codegen)
- [ ] Add backend toys for servers, API testing tools, OpenAPI mock server, etc.
- [ ] Add `VueJS` support
- [ ] Add `Angluar` support
- [ ] Introduce multiple sub folders instead of a single src (like ui, server, etc.)
- [ ] Rewrite whole codebase in TS
- [ ] Add `svgo` process
- [ ] Implement support for `presets`
- [ ] Add support for `react-docgen-typescript-loader`
- [ ] Add more verbose loggin
- [ ] Add more debug info
- [ ] Create unit tests
- [ ] Add out-of-the-box support for translations using Babel macros
- [ ] Add `parcel` support
- [ ] Add `rollup` support
- [ ] Add `babel-plugin-redux-saga` (only macro maybe?)
- [ ] Add support for locked `mhy` versions
- [ ] Optimize UI: speed
- [ ] Refact UI: Draggable, resizable, full mouse support
- [ ] Add https://github.com/pikapkg/web support
- [ ] Add https://github.com/okonet/lint-staged support
- [ ] Node 12 support for Docker image
- [ ] Setup a monorepo approach, use @mhy namespace again and refact codebase into smaller packages again.
- [ ] Add support for monorepo tools (eg. Lerna)
- [ ] Add support for dependecy presets (`npm i mhy` will still have everything together but there can be a choice to use `@mhy/core` only and install `@mhy/preset-react` separately for example.
- [ ] Auto update `mhyDependencies`?
- [ ] Run tests on deployments
- [ ] Add `storybook-addon-react-live-edit`
- [ ] Add support for command auto-complete (https://github.com/wintercounter/mhy/issues/20)
- [ ] Add new process for https://github.com/kefranabg/readme-md-generator
- [ ] Add new process for as-script
- [ ] Add new process for TypeDoc
- [ ] Add new process for serve
- [ ] Add process for https://github.com/urish/typewiz

**Comment by wintercounter** [comment]
Reserved

**Comment by wintercounter** [comment]
Reserved
